### ISSUE TITLE
Swap position of Related and Children in Parent list view

### ISSUE THREAD

**Issue by rahidelvi** [handsomecode/trello-parent-child#14]
Anytime I preview a `Parent` card, I'm usually interested in the `Children`, and only then the `Related` cards.

Would you be able to reorder the views this way?

![pc](https://cloud.githubusercontent.com/assets/5497396/19944863/f4232cba-a113-11e6-89ab-f21ebc7cdb62.png)

Thank you for creating and sharing this lovely extension.

**Comment by alexzub** [comment]
This is a very valid request and we might include it in the next update. At the very least, it should be an option in settings.

Unfortunately I don't think we'll get to it earlier than end of November.

Thank you for making this request!

**Comment by alexzub** [comment]
@rahidelvi we've implemented it as a new feature in v0.8.0: https://chrome.google.com/webstore/detail/parentchild-management-fo/flnpbgmiploomjgagfbcjlikpiehclld

You'll find an option to re-order the lists in extension settings.

Please let us know if you experience any problems with it.

Thanks!

**Comment by rahidelvi** [comment]
Thank you. It works beautifully.
