### ISSUE TITLE
Feature Request - Export Parent Child info to Excel

### ISSUE THREAD

**Issue by geneva-data** [handsomecode/trello-parent-child#44]
When exporting to Excel , the parent child information is not included in the export data. Can this be added?

**Comment by alexzub** [comment]
@geneva-data I'm afraid it's outside of what's possible to do using the limited capabilities we have of a Chrome Extension. Since all you see is just one-the-fly front-end visual adjustments, it doesn't affect the way Trello generates export data, unfortunately.

**Comment by geneva-data** [comment]
Thanks Alex,

I have a workaround. I am using another extension Trello Export which has
the capability to export custom fields and checklists. It seems that the
parent/child are being treated as a checklist so it is able to export the
data.

Once in Excel, I still need to rearrange things so I can view the related
data (Epics and User Stories) hierarchically but I will automate with a
macro at some point to make it more or less seamless.

Thanks for your great extension!

Best, Jonathan

**Comment by geneva-data** [comment]
Maybe you can see if the open source code of TrelloExport can help you to incorporate an export feature into your extension

https://chrome.google.com/webstore/detail/trelloexport/kmmnaeamjfdnbhljpedgfchjbkbomahp

http://trapias.github.io/
