### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by apkoponen** [handsomecode/trello-parent-child#5]
None of the functionality that the extension provides is visible in Trello. The extension itself and the settings seem to work fine.

**Configuration:**
OS X (Yosemite)
Chrome Version 49.0.2623.112 (64-bit)

**Comment by alexzub** [comment]
@apkoponen the hotfix is posted as v0.7.7 here https://chrome.google.com/webstore/detail/parentchild-management-fo/flnpbgmiploomjgagfbcjlikpiehclld . Uninstall and install the extension if it hasn't been updated automatically (it might take several hours for the autoupdate to work).

**Comment by apkoponen** [comment]
Thank you!
