### ISSUE TITLE
Requires reloading page

### ISSUE THREAD

**Issue by hrecook** [handsomecode/trello-parent-child#51]
Hello!
I'm really glad that there's an extension like that. Unfortunately, it doesn't work properly.
I have to reload page every time I wanna see the buttons "Child" or "Parent", and that is like it on every single card. Moreover, I have to reload page every time I wanna see established relations. 
What should I do?

**Comment by alexzub** [comment]
@hrecook We have this issue fixed on a development build, currently undergoing QA, and will post the update in the Google Store within the next several days. (cc @BennetLeff )

**Comment by BennetLeff** [comment]
This issue has been fixed by version 0.8.2 which is currently in the publishing pipeline and should be available later today.
